logistic/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from logistic import views

app_name = 'logistic'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^received/$', views.MessageView.as_view(message='Заявка успешно отправлена'), name='message'),
    url(r'^glogistics\.ru\.html/$', TemplateView.as_view(template_name='logistic/wo_sign.html'), name='wo_sign'),
]

logistic_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from logistic_site import settings

urlpatterns = [
    url(r'^', include('logistic.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logistic/models.py
from django.db import models


class SimpleRequestModel(models.Model):
    name = models.CharField(max_length=30, blank=True)
    email = models.EmailField(max_length=30)
    phone = models.CharField(max_length=30)

    is_seen = models.BooleanField(default=False)


class RequestModel(models.Model):
    name = models.CharField(max_length=30, blank=True)
    company = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=30)
    email = models.EmailField(max_length=30)
    ship_date = models.DateTimeField()
    from_address = models.CharField(max_length=30, blank=True)
    to_address = models.CharField(max_length=30, blank=True)
    price = models.PositiveIntegerField(blank=True, null=True)
    amount = models.PositiveIntegerField(blank=True, null=True)
    weight = models.PositiveIntegerField(blank=True, null=True)
    code = models.PositiveIntegerField(blank=True, null=True)
    size = models.PositiveIntegerField(blank=True, null=True)
    places = models.PositiveIntegerField(blank=True, null=True)

    is_seen = models.BooleanField(default=False)

logistic/forms.py
from django import forms

from logistic import models


class SimpleRequestForm(forms.ModelForm):
    class Meta:
        model = models.SimpleRequestModel
        fields = ['name', 'email', 'phone']


class RequestForm(forms.ModelForm):
    class Meta:
        model = models.RequestModel
        fields = [
            'name', 'company', 'email', 'phone', 'ship_date', 'from_address', 'to_address',
            'price', 'amount', 'weight', 'code', 'size', 'places'
        ]

logistic/views.py
from django.core import urlresolvers
from django.views import generic

from logistic import forms
from logistic import models


class Index(generic.CreateView):
    template_name = 'logistic/index.html'
    form_class = forms.SimpleRequestForm
    model = models.SimpleRequestModel

    def get_success_url(self):
        return urlresolvers.reverse('logistic:message')


class MessageView(generic.TemplateView):
    template_name = 'logistic/message.html'
    timeout = 0
    message = None

    def get_context_data(self, **kwargs):
        context = super(MessageView, self).get_context_data(**kwargs)
        context['timeout'] = self.timeout
        context['message'] = self.message
        return context

logistic/templates/logistic/index.html
{% load staticfiles %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Доставка</title>
  <link rel="stylesheet" href="{% static 'logistic/css/materialize.min.css' %}">
  <link rel="stylesheet" href="{% static 'logistic/css/main.css' %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<header>
  <nav>
    <div class="container">
        <div class="nav-wrapper">
            <a class="brand-logo nav__a__color__size">GOLDENLOG</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a class="nav__a__color__size">+7(916)353-56-46</a></li>
            </ul>
        </div>
    </div>
  </nav>
</header>
<main>
  <div class="welcome">
    <div class="container">
      <div class="row main__row__margin">
        <div class="col s12 main__welcome center">
          <div class="main__welcome__header__margin">
            <h3>Golden logistics</h3>
            <h4>с нами выгодно</h4>
          </div>
          <div class="main__welcome__info__margin">
            <h5>Грузоперевозки</h5>
            <h5>Узбекистан - Россия - Узбекистан</h5>
          </div>
          <div class="call-me">
            <div class="row">
              <form action="{% url 'logistic:index' %}" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="input-field col s12 m12 l4">
                  <i class="material-icons prefix">perm_identity</i>
                  {{ form.name.errors }}
                  {{ form.name | add_class:"validate" | add_class:"main__welcome__input" }}
{#                  <input id="your_name" type="text" class="validate main__welcome__input">#}
                  <label for="{{ form.name.id_for_label }}">Имя</label>
                </div>
                <div class="input-field col s12 m12 l4">
                  <i class="material-icons prefix">email</i>
                  {{ form.email.errors }}
                  {{ form.email | add_class:"validate" | add_class:"main__welcome__input" }}
{#                  <input id="email" type="text" class="validate main__welcome__input">#}
                  <label for="{{ form.email.id_for_label }}">Email</label>
                </div>
                <div class="input-field col s12 m12 l4 main__welcome__form__margin">
                  <i class="material-icons prefix">phone</i>
                  {{ form.phone.errors }}
                  {{ form.phone | add_class:"validate" | add_class:"main__welcome__input" }}
{#                  <input id="phone_number" type="text" class="validate main__welcome__input">#}
                  <label for="{{ form.phone.id_for_label }}">Номер телефона</label>
                </div>
                <input class="waves-effect waves-light btn" type="submit" value="Оформить заявку">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="specials">
    <div class="container">
      <div class="row main__row__margin">
        <div class="col s12 main__specials center">
          <div class="col s12 m12 l3">
              <div>
                  <img class="specials__img__size" src="{% static 'logistic/img/insurance.png' %}" alt="">
              </div>
              <div>
                  Страхование грузов
              </div>
          </div>
          <div class="col s12 m12 l3">
              <div>
                  <img class="specials__img__size" src="{% static 'logistic/img/tamo_work.png' %}" alt="">
              </div>
              <div>
                  Таможенное оформление
              </div>
          </div>
          <div class="col s12 m12 l3">
              <div>
                  <img class="specials__img__size" src="{% static 'logistic/img/mark_package.png' %}" alt="">
              </div>
              <div>
                  Маркировка грузов
              </div>
          </div>
          <div class="col s12 m12 l3">
              <div>
                  <img class="specials__img__size" src="{% static 'logistic/img/low_price.png' %}" alt="">
              </div>
              <div>
                  Низкие цены
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="about">
    <div class="container">
      <div class="row main__row__margin">
        <div class="col s12 main__about">
          <div>
            <h4 class="center">О компании</h4>

            <p>
              Наша компания предоставляет услуги в области международных грузоперевозок по направлениям
              Россия-Узбекистан и Узбекистан –Россия. Во главу угла мы ставим сохранность перевозимых грузов, их
              целостность и соблюдение сроков по их доставке. Также мы готовы предложить Вам дальнейший спектр услуг,
              включающий таможенное оформление, страхование и маркировку груза. Наша компания уделяет большое внимание
              поддержанию низких цен для наших клиентов, как постоянных, так и новых при сохранении безупречного
              качества обслуживания.
            </p>
          </div>
          <div class="main__about__contacts">
            <div class="main__about__contacts__header">Наши контакты</div>
            <div class="col s12 m12 l3">
              <p>Телефоны</p>
              <p>+7(916)353-56-46</p>
              <p>+7(925)917-03-04</p>
            </div>
            <div class="col s12 m12 l4">
              <p>Email</p>
              <p>{{ 'goldenlogystycs@gmail.com' | urlize }}</p>
              <p>{{ 'goldenlogystycs@gmail.com' | urlize }}</p>
            </div>
            <div class="s12 m12 l5">
              <p>Адрес</p>
              <p>Узбекистан, Ташкент, ул. Порлок, д.4</p>
            </div>

          </div>
          <div class="main__about__contacts__social">
            <div class="col s12 m12 l6 center">
                <div class="col s1">
                    <img src="{% static 'logistic/img/whats_app.png' %}" alt="" class="contacts_icons">
                </div>
                <div class="col s5 contacts__social__number_padding">
                    +998 90 347 7964
                </div>
            </div>
            <div class="col s12 m12 l6 center">
                <div class="col s1">
                    <img src="{% static 'logistic/img/Viber-Icon.png' %}" alt="" class="contacts_icons">
                </div>
                <div class="col s5 contacts__social__number_padding">
                    +7(925)917-03-04
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="form-request">
    <div class="container">
      <div class="row main__row__margin">
        <div class="col s12 main__form-request">
          <h3 class="center">Оформите заявку прямо сейчас</h3>

          <form>
            <div class="row">
              <div class="input-field col s12 m12 l3">
                <input id="full_form_name" type="text" class="validate" placeholder=" ">
                <label for="full_form_name">Имя</label>
              </div>
              <div class="input-field col s12 m12 l3">
                <input id="full_form_company" type="text" class="validate" placeholder=" ">
                <label for="full_form_company">Компания</label>
              </div>
              <div class="input-field col s12 m12 l3">
                <input id="full_form_phone" type="text" class="validate" placeholder=" ">
                <label for="full_form_phone">Контактный телефон</label>
              </div>
              <div class="input-field col s12 m12 l3">
                <input id="full_form_email" type="text" class="validate" placeholder=" ">
                <label for="full_form_email">Email</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12 m12 l3">
                <input id="full_form_send_date" type="text" class="validate" placeholder=" ">
                <label for="full_form_send_date">Дата отправки груза</label>
              </div>
              <div class="input-field col s12 m12 l5">
                <input id="full_form_loading_adress" type="text" class="validate" placeholder=" ">
                <label for="full_form_loading_adress">Адрес загрузки груза</label>
              </div>
              <div class="input-field col s12 m12 l4">
                <input id="full_form_landing_adress" type="text" class="validate" placeholder=" ">
                <label for="full_form_landing_adress">Адрес выгрузки груза</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12 m12 l1">
                <input id="full_form_cost" type="text" class="validate" placeholder=" ">
                <label for="full_form_cost">Стоимость груза</label>
              </div>
              <div class="input-field col s12 m12 l1">
                <input id="full_form_volume" type="text" class="validate" placeholder=" ">
                <label for="full_form_volume">Объем груза</label>
              </div>
              <div class="input-field col s12 m12 l2">
                <input id="full_form_weight" type="text" class="validate" placeholder=" ">
                <label for="full_form_weight">Общий вес груза</label>
              </div>
              <div class="input-field col s12 m12 l2">
                <input id="full_form_code" type="text" class="validate" placeholder=" ">
                <label for="full_form_code">Код ТН ВЭД</label>
              </div>
              <div class="input-field col s12 m12 l3">
                <input id="full_form_size" type="text" class="validate" placeholder=" ">
                <label for="full_form_size">Размеры грузовых мест</label>
              </div>
              <div class="input-field col s12 m12 l3">
                <input id="full_form_positions" type="text" class="validate" placeholder=" ">
                <label for="full_form_positions">Количество мест</label>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>

<footer>
  <div class="col s12">footer</div>
</footer>

<script src="{% static 'logistic/js/jquery.min.js' %}"></script>
<script src="{% static 'logistic/js/materialize.min.js' %}"></script>
<script src="{% static 'logistic/js/main.js' %}"></script>
</body>
</html>

logistic/templates/logistic/message.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Сообщение</title>
</head>
<body>
  <h1>{{ message }}</h1>
  {% if timeout %}
    <h1>
      Вы будете перенаправлены в личный кабинет через
      <span class="timeout-message-selector" data-redirect="{% url 'logistic:index' %}"></span>
      сек.
    </h1>
  {% endif %}
  <script type="text/javascript">
    var counter = parseInt({{ timeout }});
    var counterDisplay = $('.timeout-message-selector');
    var interval = setInterval(function() {
      counter--;
      // Display 'counter' wherever you want to display it.
      counterDisplay.text(counter);
      if (counter == 0) {
        clearInterval(interval);
        // Display a login box
        window.location.href = counterDisplay.data('redirect');
      }
    }, 1000);
  </script>
</body>
</html>

logistic/templates/logistic/wo_sign.html
bU1oR20ybExleHhHN3Y2dTVFNnAvR1lmbVNZS1labThJcDg4R0xLVXMwRT0